name: ${project.artifactId}
author: Joby
main: ${project.mainclass}
version: ${project.version}
depend: [CodCraftAPI, TagAPI]
description: First test of CodCraftAPI
commands:
   vote:
      description: Vote for a map in the lobby
      usage: /vote [mapname]
      permission: 
      permission-message: You can't vote!
   endround:
      description: Vote for a map in the lobby
      usage: /endround
      permission: 
      permission-message: You can't vote!
   CaC:
      description: Vote for a map in the lobby
      usage: /CaC
      permission: 
      permission-message: You can't vote!
   spec:
      description: Vote for a map in the lobby
      usage: /spec
      permission: 
      permission-message: You can't vote!
   a:
      description: Admins commands
      usage: /a
      permission: 
      permission-message: You can't use Admins commands
   team:
      description: teams command
      usage: /team
      permission: 
      permission-message: You can't use team command
   gui:
      description: teams command
      usage: /team
      permission: 
      permission-message: You can't use team command
   switch:
      description: switch command
      usage: /switch
      permission: 
      permission-message: You can't use team command
   Buddy:
      description: Buddy command
      usage: /Buddy
      permission: 
      permission-message: You can't use team command
      