name: CCLobbyMaker
main: com.codcraft.lobby.CCLobby
version: 0.1.001
commands: 
    send:
      description: go to be f
      usage: /send
    maker:
      description: go to be maker
      usage: /maker
