name: CCCommands
main: com.codcraft.ccommands.CCCommands
version: 0.1.002
depend: [CodCraftAPI]
commands:
   lobby:
      description: Got to lobby
      usage: /lobby
   gameinfo:
      description: Got to spawn
      usage: /gameinfo
   a:
      description: Admin Commands Admin Only!
      usage: /a
      permission: CodCraft.AdminC
      permission-message: You can't use the Admin Commands
   message:
      description: Admin Commands message Only!
      usage: /message
      permission: CodCraft.Admin
      permission-message: You can't use the Admin Commands
   CSP:
      description: Got to 
   class:
      warp:
      description: WC Warp Command
      usage: /warp <dest> or /warp <page>
      permission: codcraft.warp
   w:
      description: WC Warp Command
      usage: /w <dest> or /w <page>
      permission: codcraft.warp
   remwarp:
      description: WC Warp Command
      usage: /remwarp <warp>
      permission: codcraft.warp
   delwarp:
      description: WC Warp Command
      usage: /delwarp <warp>
      permission: codcraft.warp
   setwarp:
      description: WC Warp Command
      usage: /setwarp <warp>
      permission: codcraft.warp 
