package com.codcraft.PlayerDataViewer;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;

import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;

import com.CodCraft.api.CCAPI;
import com.codcraft.PlayerDataViewer.letters.Letter;

public class Main extends JavaPlugin {
	public Board board;
	public List<Segment> kills = new ArrayList<>();
	public List<Segment> deaths = new ArrayList<>();
	public List<Segment> wins = new ArrayList<>();
	public List<Segment> losses = new ArrayList<>();
	public List<Segment> kd = new ArrayList<>();
	public Map<String, Letter> letters = new HashMap<String, Letter>();
	public CCAPI api;
	public NewListener list;
	public String game;
	protected List<Segment> level = new ArrayList<>();
	protected List<Segment> points = new ArrayList<>();
	
	public void onEnable() {
		this.list = new NewListener(this);
		getCommand("board").setExecutor(new BoardCommand(this));
		getServer().getPluginManager().registerEvents(new NewListener(this), this);
		Line line = new Line() {
		};
		board = new Board() {
		};
		board.addLine(line);
		
		loadymls();
		final CCAPI ccapi = (CCAPI) Bukkit.getPluginManager().getPlugin("CodCraftAPI");
		if(ccapi == null) {
			getLogger().log(Level.WARNING, "API NOT FOUND");
		} else {
			this.api = ccapi;
		}
		temploadletters();
		game = "ffa";
	}
	
	private void temploadletters() {
		Letter la = new Letter() {};
		la.block2 = 0;
		la.block4 = 0;
		la.block6 = 0;
		la.block7 = 0;
		la.block8 = 0;
		la.block9 = 0;
		la.block10 = 0;
		la.block12 = 0;
		la.block13 = 0;
		la.block15 = 0;
		letters.put("a", la);
		Letter lb = new Letter() {};
		lb.block1 = 0;
		lb.block2 = 0;
		lb.block4 = 0;
		lb.block6 = 0;
		lb.block7 = 0;
		lb.block8 = 0;
		lb.block9 = 0;
		lb.block10 = 0;
		lb.block12 = 0;
		lb.block13 = 0;
		lb.block14 = 0;
		letters.put("b", lb);
		Letter lc = new Letter() {};
		lc.block1 = 0;
		lc.block2 = 0;
		lc.block3 = 0;
		lc.block4 = 0;
		lc.block7 = 0;
		lc.block10 = 0;
		lc.block13 = 0;
		lc.block14 = 0;
		lc.block15 = 0;
		letters.put("c", lc);
		Letter ld = new Letter() {};
		ld.block1 = 0;
		ld.block2 = 0;
		ld.block4 = 0;
		ld.block6 = 0;
		ld.block7 = 0;
		ld.block9 = 0;
		ld.block10 = 0;
		ld.block12 = 0;
		ld.block13 = 0;
		ld.block14 = 0;
		letters.put("d", ld);
		Letter le = new Letter() {};
		le.block1 = 0;
		le.block2 = 0;
		le.block3 = 0;
		le.block4 = 0;
		le.block7 = 0;
		le.block8 = 0;
		le.block10 = 0;
		le.block13 = 0;
		le.block14 = 0;
		le.block15 = 0;
		letters.put("e", le);
		Letter lf = new Letter() {};
		lf.block1 = 0;
		lf.block2 = 0;
		lf.block3 = 0;
		lf.block4 = 0;
		lf.block7 = 0;
		lf.block8 = 0;
		lf.block10 = 0;
		lf.block13 = 0;
		letters.put("f", lf);
		Letter lg = new Letter() {};
		lg.block2 = 0;
		lg.block4 = 0;
		lg.block7 = 0;
		lg.block8 = 0;
		lg.block10 = 0;
		lg.block12 = 0;
		lg.block14 = 0;
		letters.put("g", lg);
		Letter lh = new Letter() {};
		lh.block1 = 0;
		lh.block3 = 0;
		lh.block4 = 0;
		lh.block6 = 0;
		lh.block7 = 0;
		lh.block8 = 0;
		lh.block9 = 0;
		lh.block10 = 0;
		lh.block12 = 0;
		lh.block13 = 0;
		lh.block15 = 0;
		letters.put("h", lh);
		Letter li = new Letter() {};
		li.block1 = 0;
		li.block2 = 0;
		li.block3 = 0;
		li.block5 = 0;
		li.block8 = 0;
		li.block11 = 0;
		li.block13 = 0;
		li.block14 = 0;
		li.block15 = 0;
		letters.put("i", li);
		Letter lj = new Letter() {};
		lj.block1 = 0;
		lj.block2 = 0;
		lj.block3 = 0;
		lj.block5 = 0;
		lj.block8 = 0;
		lj.block11 = 0;
		lj.block13 = 0;
		lj.block14 = 0;
		letters.put("j", lj);
		Letter lk = new Letter() {};
		lk.block1 = 0;
		lk.block3 = 0;
		lk.block4 = 0;
		lk.block6 = 0;
		lk.block7 = 0;
		lk.block8 = 0;
		lk.block10 = 0;
		lk.block12 = 0;
		lk.block13 = 0;
		lk.block15 = 0;
		letters.put("k", lk);
		Letter ll = new Letter() {};
		ll.block1 = 0;
		ll.block4 = 0;
		ll.block7 = 0;
		ll.block10 = 0;
		ll.block13 = 0;
		ll.block14 = 0;
		ll.block15 = 0;
		letters.put("l", ll);
		Letter lm = new Letter() {};
		lm.block1 = 0;
		lm.block3 = 0;
		lm.block4 = 0;
		lm.block5 = 0;
		lm.block6 = 0;
		lm.block7 = 0;
		lm.block8 = 0;
		lm.block9 = 0;
		lm.block10 = 0;
		lm.block12 = 0;
		lm.block13 = 0;
		lm.block15 = 0;
		letters.put("m", lm);
		Letter ln = new Letter() {};
		ln.block1 = 0;
		ln.block4 = 0;
		ln.block5 = 0;
		ln.block7 = 0;
		ln.block9 = 0;
		ln.block10 = 0;
		ln.block12 = 0;
		ln.block13 = 0;
		ln.block15 = 0;
		letters.put("n", ln);
		Letter lo = new Letter() {};
		lo.block1 = 0;
		lo.block2 = 0;
		lo.block3 = 0;
		lo.block4 = 0;
		lo.block6 = 0;
		lo.block7 = 0;
		lo.block9 = 0;
		lo.block10 = 0;
		lo.block12 = 0;
		lo.block13 = 0;
		lo.block14 = 0;
		lo.block15 = 0;
		letters.put("o", lo);
		Letter lp = new Letter() {};
		lp.block1 = 0;
		lp.block2 = 0;
		lp.block3 = 0;
		lp.block4 = 0;
		lp.block6 = 0;
		lp.block7 = 0;
		lp.block8 = 0;
		lp.block9 = 0;
		lp.block10 = 0;
		lp.block13 = 0;
		letters.put("p", lp);
		Letter lq = new Letter() {};
		lq.block1 = 0;
		lq.block2 = 0;
		lq.block3 = 0;
		lq.block4 = 0;
		lq.block6 = 0;
		lq.block7 = 0;
		lq.block9 = 0;
		lq.block10 = 0;
		lq.block11 = 0;
		lq.block15 = 0;
		letters.put("q", lq);
		Letter lr = new Letter() {};
		lr.block1 = 0;
		lr.block2 = 0;
		lr.block3 = 0;
		lr.block4 = 0;
		lr.block6 = 0;
		lr.block7 = 0;
		lr.block8 = 0;
		lr.block9 = 0;
		lr.block10 = 0;
		lr.block11 = 0;
		lr.block13 = 0;
		lr.block15 = 0;
		letters.put("r", lr);
		Letter ls = new Letter() {};
		ls.block2 = 0;
		ls.block3 = 0;
		ls.block4 = 0;
		ls.block8 = 0;
		ls.block12 = 0;
		ls.block13 = 0;
		ls.block14 = 0;
		letters.put("s", ls);
		Letter lt = new Letter() {};
		lt.block1 = 0;
		lt.block2 = 0;
		lt.block3 = 0;
		lt.block5 = 0;
		lt.block8 = 0;
		lt.block11 = 0;
		lt.block14 = 0;
		letters.put("t", lt);
		Letter lu = new Letter() {};
		lu.block1 = 0;
		lu.block3 = 0;
		lu.block4 = 0;
		lu.block6 = 0;
		lu.block7 = 0;
		lu.block9 = 0;
		lu.block10 = 0;
		lu.block12 = 0;
		lu.block13 = 0;
		lu.block14 = 0;
		lu.block15 = 0;
		letters.put("u", lu);
		Letter lv = new Letter() {};
		lv.block1 = 0;
		lv.block3 = 0;
		lv.block4 = 0;
		lv.block6 = 0;
		lv.block7 = 0;
		lv.block9 = 0;
		lv.block10 = 0;
		lv.block12 = 0;
		lv.block14 = 0;
		letters.put("v", lv);
		Letter lw = new Letter() {};
		lw.block1 = 0;
		lw.block3 = 0;
		lw.block4 = 0;
		lw.block6 = 0;
		lw.block7 = 0;
		lw.block8 = 0;
		lw.block9 = 0;
		lw.block10 = 0;
		lw.block11 = 0;
		lw.block12 = 0;
		lw.block13 = 0;
		lw.block15 = 0;
		letters.put("w", lw);
		Letter lx = new Letter() {};
		lx.block1 = 0;
		lx.block3 = 0;
		lx.block4 = 0;
		lx.block7 = 0;
		lx.block8 = 0;
		lx.block10 = 0;
		lx.block12 = 0;
		lx.block13 = 0;
		lx.block15 = 0;
		letters.put("x", lx);
		Letter ly = new Letter() {};
		ly.block1 = 0;
		ly.block3 = 0;
		ly.block4 = 0;
		ly.block6 = 0;
		ly.block7 = 0;
		ly.block8 = 0;
		ly.block9 = 0;
		ly.block12 = 0;
		ly.block13 = 0;
		ly.block14 = 0;
		ly.block15 = 0;
		letters.put("y", ly);
		Letter lz = new Letter() {};
		lz.block1 = 0;
		lz.block2 = 0;
		lz.block3 = 0;
		lz.block6 = 0;
		lz.block8 = 0;
		lz.block10 = 0;
		lz.block13 = 0;
		lz.block14 = 0;
		lz.block15 = 0;
		letters.put("z", lz);
		Letter l_ = new Letter() {};
		l_.block13 = 0;
		l_.block14 = 0;
		l_.block15 = 0;
		letters.put("_", l_);
		Letter l1 = new Letter() {};
		l1.block2 = 0;
		l1.block5 = 0;
		l1.block8 = 0;
		l1.block8 = 0;
		l1.block11 = 0;
		l1.block14 = 0;
		letters.put("1", l1);
		Letter l2 = new Letter() {};
		l2.block1 = 0;
		l2.block2 = 0;
		l2.block3 = 0;
		l2.block6 = 0;
		l2.block7 = 0;
		l2.block8 = 0;
		l2.block9 = 0;
		l2.block10 = 0;
		l2.block13 = 0;
		l2.block14 = 0;
		l2.block15 = 0;
		letters.put("2", l2);
		Letter l3 = new Letter() {};
		l3.block1 = 0;
		l3.block2 = 0;
		l3.block3 = 0;
		l3.block6 = 0;
		l3.block7 = 0;
		l3.block8 = 0;
		l3.block9 = 0;
		l3.block12 = 0;
		l3.block13 = 0;
		l3.block14 = 0;
		l3.block15 = 0;
		letters.put("3", l3);
		Letter l4r = new Letter() {};
		l4r.block1 = 0;
		l4r.block3 = 0;
		l4r.block4 = 0;
		l4r.block6 = 0;
		l4r.block7 = 0;
		l4r.block8 = 0;
		l4r.block9 = 0;
		l4r.block12 = 0;
		l4r.block15 = 0;
		letters.put("4", l4r);
		Letter l5 = new Letter() {};
		l5.block1 = 0;
		l5.block2 = 0;
		l5.block3 = 0;
		l5.block4 = 0;
		l5.block7 = 0;
		l5.block8 = 0;
		l5.block9 = 0;
		l5.block12 = 0;
		l5.block13 = 0;
		l5.block14 = 0;
		l5.block15 = 0;
		letters.put("5", l5);
		Letter l6 = new Letter() {};
		l6.block1 = 0;
		l6.block2 = 0;
		l6.block3 = 0;
		l6.block4 = 0;
		l6.block7 = 0;
		l6.block8 = 0;
		l6.block9 = 0;
		l6.block10 = 0;
		l6.block12 = 0;
		l6.block13 = 0;
		l6.block14 = 0;
		l6.block15 = 0;
		letters.put("6", l6);
		Letter l7 = new Letter() {};
		l7.block1 = 0;
		l7.block2 = 0;
		l7.block3 = 0;;
		l7.block6 = 0;
		l7.block9 = 0;
		l7.block12 = 0;
		l7.block15 = 0;
		letters.put("7", l7);
		Letter l8 = new Letter() {};
		l8.block1 = 0;
		l8.block2 = 0;
		l8.block3 = 0;
		l8.block4 = 0;
		l8.block6 = 0;
		l8.block7 = 0;
		l8.block8 = 0;
		l8.block9 = 0;
		l8.block10 = 0;
		l8.block12 = 0;
		l8.block13 = 0;
		l8.block14 = 0;
		l8.block15 = 0;
		letters.put("8", l8);
		Letter l9 = new Letter() {};
		l9.block1 = 0;
		l9.block2 = 0;
		l9.block3 = 0;;
		l9.block4 = 0;
		l9.block6 = 0;
		l9.block7 = 0;
		l9.block8 = 0;
		l9.block9 = 0;
		l9.block12 = 0;
		l9.block13 = 0;
		l9.block14 = 0;
		l9.block15 = 0;
		letters.put("9", l9);
		Letter l0 = new Letter() {};
		l0.block1 = 0;
		l0.block2 = 0;
		l0.block3 = 0;;
		l0.block4 = 0;
		l0.block6 = 0;
		l0.block7 = 0;
		l0.block9 = 0;
		l0.block10 = 0;
		l0.block12 = 0;
		l0.block13 = 0;
		l0.block14 = 0;
		l0.block15 = 0;
		letters.put("0", l0);
	}

	private void loadymls() {
		World world = Bukkit.getWorld("world");
		File Sign = new File(getDataFolder(), "games.yml");
		YamlConfiguration Gamesconfig = YamlConfiguration.loadConfiguration(Sign);
		game = Gamesconfig.getString("board");
		for(String Signstring : Gamesconfig.getConfigurationSection("segment").getKeys(false)) {
			int i = 1;
			Segment seg = new Segment();
			for(String Location : Gamesconfig.getConfigurationSection("segment."+Signstring).getKeys(false)) {
				Location Block = new Location(world, 
						Double.parseDouble(Gamesconfig.getString("segment."+Signstring+"."+Location+".x")), 
						Double.parseDouble(Gamesconfig.getString("segment."+Signstring+"."+Location+".y")), 
						Double.parseDouble(Gamesconfig.getString("segment."+Signstring+"."+Location+".z")));
				if(i == 1) seg.loc1 = Block;
				else if (i == 2) seg.loc2 = Block;
				else if (i == 3) seg.loc3 = Block;
				else if (i == 4) seg.loc4 = Block;
				else if (i == 5) seg.loc5 = Block;
				else if (i == 6) seg.loc6 = Block;
				else if (i == 7) seg.loc7 = Block;
				else if (i == 8) seg.loc8 = Block;
				else if (i == 9) seg.loc9 = Block;
				else if (i == 10) seg.loc10 = Block;
				else if (i == 11) seg.loc11 = Block;
				else if (i == 12) seg.loc12 = Block;
				else if (i == 13) seg.loc13 = Block;
				else if (i == 14) seg.loc14 = Block;
				else if (i == 15) seg.loc15 = Block;
				i++;
				
			}
			board.lines.get(0).segmants.add(seg);
		}

		for(String name : Gamesconfig.getConfigurationSection("extra").getKeys(false)) {
			for(String name2 : Gamesconfig.getConfigurationSection("extra."+name).getKeys(false)) {
				int i = 1;
				Segment seg = new Segment();		
				for(String location : Gamesconfig.getConfigurationSection("extra."+name+"."+name2).getKeys(false)) {
					getLogger().info(name+": "+ name2+": "+location+": ");
					Location Block = new Location(world, 
							Double.parseDouble(Gamesconfig.getString("extra"+"."+name+"."+name2+"."+location+".x")), 
							Double.parseDouble(Gamesconfig.getString("extra"+"."+name+"."+name2+"."+location+".y")), 
							Double.parseDouble(Gamesconfig.getString("extra"+"."+name+"."+name2+"."+location+".z")));
					if(i == 1) seg.loc1 = Block;
					else if (i == 2) seg.loc2 = Block;
					else if (i == 3) seg.loc3 = Block;
					else if (i == 4) seg.loc4 = Block;
					else if (i == 5) seg.loc5 = Block;
					else if (i == 6) seg.loc6 = Block;
					else if (i == 7) seg.loc7 = Block;
					else if (i == 8) seg.loc8 = Block;
					else if (i == 9) seg.loc9 = Block;
					else if (i == 10) seg.loc10 = Block;
					else if (i == 11) seg.loc11 = Block;
					else if (i == 12) seg.loc12 = Block;
					else if (i == 13) seg.loc13 = Block;
					else if (i == 14) seg.loc14 = Block;
					else if (i == 15) seg.loc15 = Block;
					i++;
				}
				if(name.equalsIgnoreCase("kills")) {
					kills.add(0, seg);
				} else if (name.equalsIgnoreCase("deaths")) {
					deaths.add(0,seg);
				} else if (name.equalsIgnoreCase("kd")) {
					kd.add(0, seg);
				} else if (name.equalsIgnoreCase("wins")) {
					wins.add(0, seg);
				} else if (name.equalsIgnoreCase("losses")) {
					losses.add(0, seg);
				} else if (name.equalsIgnoreCase("level")) {
					level.add(0, seg);
				} else if (name.equalsIgnoreCase("point")) {
					points.add(0, seg);
				}
			}
		}

	}	
}
