name: Infected
main: com.codcraft.infected.CodCraftInfected
version: 1
depend: [CodCraftAPI, TagAPI]
description: First test of CodCraftAPI
commands:
   vote:
      description: vote
      usage: /vote